include:
  - db.yml

services:
  # Production backend (using GitHub image)
  backend:
    image: ghcr.io/bbq-gmbh/backend:latest
    profiles: ["prod"]
    platform: linux/arm64
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/fs-backend
      JWT_SECRET_KEY: ${JWT_SECRET_KEY:-secret}
      JWT_ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      REFRESH_TOKEN_EXPIRE_DAYS: 7
    depends_on:
      postgres:
        condition: service_healthy

  # Production frontend (using GitHub image)
  frontend:
    image: ghcr.io/bbq-gmbh/frontend2:latest
    profiles: ["prod"]
    ports:
      - "3000:3000"
    environment:
      BACKEND_URL: http://backend:3001
    depends_on:
      - backend